PRODUCTS = [
    {
        "sku": "ELE-FONE",
        "name": "Fone Bluetooth Aura",
        "category": "Eletrônicos",
        "target_audience": "Pessoas que ouvem música na rotina",
        "technical_attributes": {"conectividade": "Bluetooth 5.3", "autonomia": "24 horas"},
        "key_benefits": ["Uso sem fios", "Estojo para transporte"],
    },
    {
        "sku": "ELE-TECLADO",
        "name": "Teclado compacto Pixel",
        "category": "Informática",
        "target_audience": "Profissionais com mesas pequenas",
        "technical_attributes": {"layout": "ABNT2", "conexão": "USB", "formato": "60%"},
        "key_benefits": ["Ocupa menos espaço", "Conexão por cabo"],
    },
    {
        "sku": "ELE-LUZ",
        "name": "Luminária LED Mesa",
        "category": "Iluminação",
        "target_audience": "Estudantes em home office",
        "technical_attributes": {"potência": "8 W", "níveis": "3 intensidades"},
        "key_benefits": ["Intensidade ajustável", "Iluminação direcionada"],
    },
    {
        "sku": "COS-SERUM",
        "name": "Sérum facial Essência",
        "category": "Cosméticos",
        "target_audience": "Adultos que buscam uma rotina de cuidados",
        "technical_attributes": {"volume": "30 ml", "textura": "gel"},
        "key_benefits": ["Textura leve", "Aplicação com conta-gotas"],
    },
    {
        "sku": "COS-SABONETE",
        "name": "Sabonete líquido Botânico",
        "category": "Higiene pessoal",
        "target_audience": "Pessoas que preferem sabonete líquido",
        "technical_attributes": {"volume": "250 ml", "fragrância": "lavanda"},
        "key_benefits": ["Embalagem com válvula", "Fragrância de lavanda"],
    },
    {
        "sku": "COS-CREME",
        "name": "Creme para mãos Toque",
        "category": "Cuidados pessoais",
        "target_audience": "Pessoas que levam cosméticos na bolsa",
        "technical_attributes": {"volume": "50 g", "embalagem": "bisnaga"},
        "key_benefits": ["Formato compacto", "Aplicação prática"],
    },
    {
        "sku": "VES-CAMISETA",
        "name": "Camiseta algodão Essencial",
        "category": "Vestuário",
        "target_audience": "Adultos que buscam roupas casuais",
        "technical_attributes": {"material": "100% algodão", "cor": "azul", "tamanhos": "P ao GG"},
        "key_benefits": ["Tecido de algodão", "Modelagem casual"],
    },
    {
        "sku": "VES-JAQUETA",
        "name": "Jaqueta leve Urbana",
        "category": "Moda urbana",
        "target_audience": "Pessoas com rotina ao ar livre",
        "technical_attributes": {"material": "poliéster", "fechamento": "zíper"},
        "key_benefits": ["Bolsos laterais", "Fechamento com zíper"],
    },
    {
        "sku": "VES-MOCHILA",
        "name": "Mochila Campus",
        "category": "Acessórios",
        "target_audience": "Estudantes universitários",
        "technical_attributes": {"capacidade": "20 litros", "compartimento": "notebook até 15 polegadas"},
        "key_benefits": ["Organização em compartimentos", "Espaço para notebook"],
    },
    {
        "sku": "CAS-GARRAFA",
        "name": "Garrafa inox Trilhas",
        "category": "Casa e lazer",
        "target_audience": "Pessoas que transportam água diariamente",
        "technical_attributes": {"volume": "600 ml", "material": "aço inox"},
        "key_benefits": ["Recipiente reutilizável", "Tampa rosqueável"],
    },
]
